#Alacritty configuration

[shell]
program = "/usr/bin/bash"

[scrolling]
history = 100000

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"
decorations = "None"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[cursor]
blink_timeout = 0
blink_interval = 600

[cursor.style]
blinking = "Always"

[font]
size = 15

[font.normal]
family = "Monego"
style = "Regular"

[font.italic]
family = "Monego"
style = "Italic"

[font.bold]
family = "Monego"
style = "Bold"

[font.bold_italic]
family = "Monego"
style = "Bold Italic"


[mouse]
hide_when_typing = true
